const investigators = [
  {
    id: 1,
    name: "Victor Ashford",
    image: "https://i.pravatar.cc/300?img=11",
    category: "Surveillance",
    location: "Mumbai, Maharashtra",
    rating: 4.9,
    experience: 18,
    specialization: "Corporate Espionage & Counter-Surveillance",
    description: "Former RAW intelligence officer with 18 years of field experience. Specializes in corporate espionage countermeasures and high-stakes surveillance operations.",
    skills: ["Counter-Surveillance", "TSCM Bug Sweeping", "Corporate Intelligence", "Asset Tracing", "Undercover Operations"],
    languages: ["English", "Hindi", "Marathi"],
    badge: "Top Rated",
    cases: [
      { title: "Corporate IP Theft", year: 2023, outcome: "Evidence secured, case won in court" },
      { title: "Boardroom Mole Investigation", year: 2022, outcome: "Leak identified within 2 weeks" },
      { title: "Executive Stalker Case", year: 2022, outcome: "Perpetrator apprehended, client safe" },
    ],
    reviews: [
      { name: "Rajiv M.", rating: 5, text: "Exceptional discretion and professionalism. Delivered ironclad evidence." },
      { name: "Priya S.", rating: 5, text: "Victor cracked a year-long leak in our firm within days. Worth every rupee." },
      { name: "Anil K.", rating: 4, text: "Very thorough. Communication could be a bit more frequent but results speak." },
    ]
  },
  {
    id: 2,
    name: "Seema Nair",
    image: "https://i.pravatar.cc/300?img=47",
    category: "Missing Person",
    location: "Delhi, NCR",
    rating: 4.8,
    experience: 12,
    specialization: "Missing Persons & Child Recovery",
    description: "Licensed investigator with 12 years tracking missing persons and runaway minors. Known for closing cold cases that official agencies abandoned.",
    skills: ["Cold Case Analysis", "Social Network Mapping", "Digital Footprint Tracking", "Witness Interviews", "Psychological Profiling"],
    languages: ["English", "Hindi", "Malayalam"],
    badge: "Verified Expert",
    cases: [
      { title: "Runaway Teenager Recovery", year: 2023, outcome: "Child found in Rajasthan, reunited" },
      { title: "Elderly Dementia Patient", year: 2023, outcome: "Located within 48 hours" },
      { title: "Cold Case — 2-Year Disappearance", year: 2022, outcome: "Individual traced internationally" },
    ],
    reviews: [
      { name: "Meena R.", rating: 5, text: "Seema found my daughter when police gave up. She is an angel." },
      { name: "Thomas V.", rating: 5, text: "Relentless, compassionate, and incredibly effective." },
      { name: "Sunita P.", rating: 4, text: "Very empathetic approach. Kept us updated at every step." },
    ]
  },
  {
    id: 3,
    name: "Arjun Khanna",
    image: "https://i.pravatar.cc/300?img=15",
    category: "Fraud",
    location: "Bengaluru, Karnataka",
    rating: 4.7,
    experience: 9,
    specialization: "Financial Fraud & Cyber Crime",
    description: "Ex-cybercrime division consultant with deep expertise in digital forensics, crypto tracing, and financial fraud investigation.",
    skills: ["Crypto Tracing", "Digital Forensics", "Financial Audits", "OSINT", "Phishing Investigation"],
    languages: ["English", "Hindi", "Kannada"],
    badge: "Cyber Specialist",
    cases: [
      { title: "₹4 Crore Startup Fraud", year: 2023, outcome: "Funds traced, FIR filed successfully" },
      { title: "CEO Impersonation Scheme", year: 2023, outcome: "Network dismantled, 3 arrested" },
      { title: "KYC Fraud Ring", year: 2022, outcome: "Documentation provided to CBI" },
    ],
    reviews: [
      { name: "Deepak B.", rating: 5, text: "Arjun traced crypto worth ₹80L that we thought was gone forever." },
      { name: "Kiran M.", rating: 4, text: "Technical brilliance. The digital audit report was court-ready." },
      { name: "Ananya R.", rating: 5, text: "Highly recommend for any digital fraud case. Meticulous and fast." },
    ]
  },
  {
    id: 4,
    name: "Lakshmi Iyer",
    image: "https://i.pravatar.cc/300?img=44",
    category: "Background Check",
    location: "Chennai, Tamil Nadu",
    rating: 4.6,
    experience: 14,
    specialization: "Pre-Matrimonial & Employment Verification",
    description: "Trusted by over 400 families and 60 corporates for discreet background verification. Specializes in pre-matrimonial checks and asset declaration audits.",
    skills: ["Matrimonial Screening", "Employment Verification", "Criminal History Check", "Address Verification", "Reference Audit"],
    languages: ["English", "Tamil", "Telugu"],
    badge: "Family Trust Specialist",
    cases: [
      { title: "Pre-Matrimonial Screening", year: 2023, outcome: "Hidden prior marriage uncovered" },
      { title: "Senior Executive Vetting", year: 2023, outcome: "Falsified credentials exposed" },
      { title: "Property Fraud Detection", year: 2022, outcome: "Duplicate ownership claim identified" },
    ],
    reviews: [
      { name: "Ravi S.", rating: 5, text: "Lakshmi saved our family from a disaster. Her work is thorough and fast." },
      { name: "Kavita N.", rating: 4, text: "Very professional. The report detail was impressive." },
      { name: "Suresh I.", rating: 5, text: "Recommended by our lawyer. Did not disappoint at all." },
    ]
  },
  {
    id: 5,
    name: "Dev Malhotra",
    image: "https://i.pravatar.cc/300?img=53",
    category: "Surveillance",
    location: "Pune, Maharashtra",
    rating: 4.5,
    experience: 7,
    specialization: "Matrimonial & Spousal Surveillance",
    description: "Specializes in sensitive domestic cases including infidelity investigations. Provides legally admissible photographic and video evidence.",
    skills: ["Mobile Surveillance", "Video Documentation", "Evidence Packaging", "GPS Tracking (Legal)", "Witness Coordination"],
    languages: ["English", "Hindi", "Marathi"],
    badge: null,
    cases: [
      { title: "Spousal Fidelity Case", year: 2023, outcome: "Evidence delivered within 7 days" },
      { title: "Matrimonial Asset Dispute", year: 2023, outcome: "Hidden property discovered" },
      { title: "Custody Investigation", year: 2022, outcome: "Court-accepted evidence package" },
    ],
    reviews: [
      { name: "Pooja D.", rating: 5, text: "Dev handled a very painful case with utmost sensitivity and efficiency." },
      { name: "Rohit A.", rating: 4, text: "Very discreet. My identity was never revealed." },
      { name: "Neha T.", rating: 4, text: "Good work, would have liked faster turnaround." },
    ]
  },
  {
    id: 6,
    name: "Farah Siddiqui",
    image: "https://i.pravatar.cc/300?img=41",
    category: "Missing Person",
    location: "Hyderabad, Telangana",
    rating: 4.8,
    experience: 11,
    specialization: "Runaway Youth & Human Trafficking Cases",
    description: "Awarded investigator collaborating with anti-trafficking NGOs. Has directly contributed to rescuing over 60 trafficking victims.",
    skills: ["Network Intelligence", "Informant Management", "Field Investigation", "Victim Support Coordination", "Legal Documentation"],
    languages: ["English", "Hindi", "Urdu", "Telugu"],
    badge: "Humanitarian Award",
    cases: [
      { title: "Trafficking Ring Exposure", year: 2023, outcome: "12 victims rescued, ring dismantled" },
      { title: "Missing College Student", year: 2023, outcome: "Found in another state, safe" },
      { title: "Domestic Violence Escape", year: 2022, outcome: "Victim relocated and protected" },
    ],
    reviews: [
      { name: "Yasmin K.", rating: 5, text: "Farah brought my sister home. I owe her everything." },
      { name: "NGO Saheli", rating: 5, text: "Our most reliable partner investigator. Fearless and methodical." },
      { name: "Arun B.", rating: 5, text: "Farah went above and beyond. True hero." },
    ]
  },
  {
    id: 7,
    name: "Samir Roy",
    image: "https://i.pravatar.cc/300?img=60",
    category: "Fraud",
    location: "Kolkata, West Bengal",
    rating: 4.4,
    experience: 15,
    specialization: "Insurance & Property Fraud",
    description: "Veteran investigator focusing on insurance fraud and property dispute cases. Has testified as an expert witness in over 30 court cases.",
    skills: ["Insurance Investigation", "Property Due Diligence", "Document Forgery Detection", "Expert Witness", "Land Record Audits"],
    languages: ["English", "Hindi", "Bengali"],
    badge: "Court Specialist",
    cases: [
      { title: "₹2Cr Insurance Claim Fraud", year: 2023, outcome: "Fraudulent claim rejected, investigator testified" },
      { title: "Property Title Fraud", year: 2022, outcome: "Original owner rights restored" },
      { title: "Fake Accident Claim Ring", year: 2022, outcome: "6 perpetrators prosecuted" },
    ],
    reviews: [
      { name: "SBI Insurance", rating: 4, text: "Samir's court experience makes him invaluable for contested cases." },
      { name: "Bimal C.", rating: 4, text: "Methodical and very knowledgeable about legal procedure." },
      { name: "Ria G.", rating: 5, text: "His document analysis is next level. Found the fake stamps no one else saw." },
    ]
  },
  {
    id: 8,
    name: "Preethi Varma",
    image: "https://i.pravatar.cc/300?img=35",
    category: "Background Check",
    location: "Kochi, Kerala",
    rating: 4.9,
    experience: 10,
    specialization: "Corporate Due Diligence & Vendor Screening",
    description: "Harvard-certified compliance professional turned investigator. Provides institutional-grade background checks for corporates and PE firms.",
    skills: ["Corporate Due Diligence", "Vendor Screening", "AML Checks", "Reputational Risk Analysis", "Global Database Access"],
    languages: ["English", "Malayalam", "Tamil"],
    badge: "Top Rated",
    cases: [
      { title: "PE Fund KYC Investigation", year: 2023, outcome: "Promoter fraud exposed pre-deal" },
      { title: "C-Suite Hire Vetting", year: 2023, outcome: "Falsified Harvard degree uncovered" },
      { title: "Vendor Network Audit", year: 2022, outcome: "Ghost vendor scheme dismantled" },
    ],
    reviews: [
      { name: "Sequoia Capital", rating: 5, text: "Preethi's due diligence saved us from a catastrophic investment." },
      { name: "Meenakshi T.", rating: 5, text: "Thorough, fast, and board-presentable reports." },
      { name: "Anand P.", rating: 5, text: "By far the most detail-oriented investigator I've worked with." },
    ]
  }
];
